% Organ Fails

organs_failure=[sum(liver_failure) sum(renal_failure) sum(heart_failure) sum(neuro_failure) ...
    sum(lung_failure) sum(infection_failure) sum(blood_failure)];
organs_alarm=[sum(liver_alarm) sum(renal_alarm) sum(heart_alarm) sum(neuro_alarm) ...
    sum(lung_alarm) sum(infection_alarm) sum(blood_alarm)];
org_alarm=[sum(liver_alarm') sum(renal_alarm') sum(heart_alarm') sum(neuro_alarm') ...
    sum(lung_alarm') sum(infection_alarm') sum(blood_alarm')];
% fail_organs=[fail_liver fail_renal fail_heart fail_neuro fail_lung ...
%     fail_infection fail_blood];
% failure_organs=[failure_liver failure_renal failure_heart ...
%     failure_lung failure_infection failure_blood];